databases:
  - name: ejfarms_db
    plan: free
    databaseName: hatchery
    user: emmanueleg

services:
  - type: web
    plan: free
    name: ejfarms
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ejfarms_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
